
GET http://localhost:3003/turma/active
content-type: application/json

###

POST http://localhost:3003/turma/add 
content-type: application/json

{
"nome": "moreira", "modulo": "0"
}

###

PUT http://localhost:3003/turma/change
content-type: application/json

{
"id": "1650660608251", "modulo": "2"

}

###

POST http://localhost:3003/estudante
content-type: application/json

{
    "nome":"matheus",
    "email":"matheus@gmail.com",
    "data_nasc": "1998/05/01",
    "turma_id": "1650662512239"
}

###
GET http://localhost:3003/estudante
content-type: application/json

{
    "nome":"joao"
}

###

PUT http://localhost:3003/estudante/edit
content-type: application/json

{
    "turma_id":"1650662710698",
    "id":"1650849241093"
}


###
POST http://localhost:3003/docente 
content-type: application/json

   {
    "id":5,
    "nome":"Damiao",
    "email":"dami3@gmail.com",
    "data_nasc":"1965-01-10",
"turma_id": 1
    }


### 
GET http://localhost:3003/docente 
content-type: application/json

{
"nome":"damiao"
}


###
PUT http://localhost:3003/docente/edit 
content-type: application/json

{
"nome": "Fernada",
"turma_id": "1650913250972"
}








